@isTest
private class skedMappingConfigController_Test {
    @isTest
    static void mappingConfigController_Test() {
        skedMappingConfigContainer.mappingConfigModel accountModel = new skedMappingConfigContainer.accountMappingConfigFactory().process();
        skedMappingConfigContainer.mappingConfigModel activityModel = new skedMappingConfigContainer.activityMappingConfigFactory().process();
        skedMappingConfigContainer.mappingConfigModel activityResourceModel = new skedMappingConfigContainer.activityResourceMappingConfigFactory().process();
        skedMappingConfigContainer.mappingConfigModel availabilityModel = new skedMappingConfigContainer.availabilityMappingConfigFactory().process();
        skedMappingConfigContainer.mappingConfigModel availabilityPatternModel = new skedMappingConfigContainer.availabilityPatternMappingConfigFactory().process();
        skedMappingConfigContainer.mappingConfigModel availabilityPatternResourceModel = new skedMappingConfigContainer.availabilityPatternResourceMappingConfigFactory().process();
        skedMappingConfigContainer.mappingConfigModel availabilityTemplateModel = new skedMappingConfigContainer.availabilityTemplateMappingConfigFactory().process();
        skedMappingConfigContainer.mappingConfigModel availabilityTemplateEntryModel = new skedMappingConfigContainer.availabilityTemplateEntryMappingConfigFactory().process();
        skedMappingConfigContainer.mappingConfigModel availabilityTemplateResourceModel = new skedMappingConfigContainer.availabilityTemplateResourceMappingConfigFactory().process();
        skedMappingConfigContainer.mappingConfigModel biomedCollectionOpCenterModel = new skedMappingConfigContainer.biomedCollectionOpCenterMappingConfigFactory().process();
        skedMappingConfigContainer.mappingConfigModel caseModel = new skedMappingConfigContainer.caseMappingConfigFactory().process();
        skedMappingConfigContainer.mappingConfigModel clientAvailabilityModel = new skedMappingConfigContainer.clientAvailabilityMappingConfigFactory().process();
        skedMappingConfigContainer.mappingConfigModel contactModel = new skedMappingConfigContainer.contactMappingConfigFactory().process();
        skedMappingConfigContainer.mappingConfigModel customAvailabilityModel = new skedMappingConfigContainer.customAvailabilityMappingConfigFactory().process();
        skedMappingConfigContainer.mappingConfigModel driveModel = new skedMappingConfigContainer.driveMappingConfigFactory().process();
        skedMappingConfigContainer.mappingConfigModel exceptionModel = new skedMappingConfigContainer.exceptionMappingConfigFactory().process();
        skedMappingConfigContainer.mappingConfigModel holidayModel = new skedMappingConfigContainer.holidayMappingConfigFactory().process();
        skedMappingConfigContainer.mappingConfigModel holidayRegionModel = new skedMappingConfigContainer.holidayRegionMappingConfigFactory().process();
        skedMappingConfigContainer.mappingConfigModel jobModel = new skedMappingConfigContainer.jobMappingConfigFactory().process();
        skedMappingConfigContainer.mappingConfigModel jobAllocationModel = new skedMappingConfigContainer.jobAllocationMappingConfigFactory().process();
        skedMappingConfigContainer.mappingConfigModel jobTagModel = new skedMappingConfigContainer.jobTagMappingConfigFactory().process();
        skedMappingConfigContainer.mappingConfigModel linkedDrivesModel = new skedMappingConfigContainer.linkedDrivesMappingConfigFactory().process();
        skedMappingConfigContainer.mappingConfigModel locationModel = new skedMappingConfigContainer.locationMappingConfigFactory().process();
        skedMappingConfigContainer.mappingConfigModel locationAvailabilityModel = new skedMappingConfigContainer.locationAvailabilityMappingConfigFactory().process();
        skedMappingConfigContainer.mappingConfigModel locationResourceScoreModel = new skedMappingConfigContainer.locationResourceScoreMappingConfigFactory().process();
        skedMappingConfigContainer.mappingConfigModel recurringScheduleModel = new skedMappingConfigContainer.recurringScheduleMappingConfigFactory().process();
        skedMappingConfigContainer.mappingConfigModel regionModel = new skedMappingConfigContainer.regionMappingConfigFactory().process();
        skedMappingConfigContainer.mappingConfigModel resourceModel = new skedMappingConfigContainer.resourceMappingConfigFactory().process();
        skedMappingConfigContainer.mappingConfigModel resourceBiomedCollectionOpModel = new skedMappingConfigContainer.resourceBiomedCollectionOpMappingConfigFactory().process();
        skedMappingConfigContainer.mappingConfigModel resourceJobOfferModel = new skedMappingConfigContainer.resourceJobOfferMappingConfigFactory().process();
        skedMappingConfigContainer.mappingConfigModel resourceOverrideModel = new skedMappingConfigContainer.resourceOverrideMappingConfigFactory().process();
        skedMappingConfigContainer.mappingConfigModel resourceRegionModel = new skedMappingConfigContainer.resourceRegionMappingConfigFactory().process();
        skedMappingConfigContainer.mappingConfigModel resourceTagModel = new skedMappingConfigContainer.resourceTagMappingConfigFactory().process();
        skedMappingConfigContainer.mappingConfigModel siteCollectionOpModel = new skedMappingConfigContainer.siteCollectionOperationMappingConfigFactory().process();
        skedMappingConfigContainer.mappingConfigModel staffingBudgetAvailabilityModel = new skedMappingConfigContainer.staffingBudgetAvailabilityMappingConfigFactory().process();
        skedMappingConfigContainer.mappingConfigModel staffingBudgetModel = new skedMappingConfigContainer.staffingBudgetMappingConfigFactory().process();
        skedMappingConfigContainer.mappingConfigModel staffingBudgetCollectionOpModel = new skedMappingConfigContainer.staffingBudgetCollectionOpMappingConfigFactory().process();
        skedMappingConfigContainer.mappingConfigModel staffingBudgetSiteModel = new skedMappingConfigContainer.staffingBudgetSiteMappingConfigFactory().process();
        skedMappingConfigContainer.mappingConfigModel tagModel = new skedMappingConfigContainer.tagMappingConfigFactory().process();
        skedMappingConfigContainer.mappingConfigModel territoryModel = new skedMappingConfigContainer.territoryMappingConfigFactory().process();
        skedMappingConfigContainer.mappingConfigModel userModel = new skedMappingConfigContainer.userMappingConfigFactory().process();
        skedMappingConfigContainer.mappingConfigModel userFilterModel = new skedMappingConfigContainer.userFilterMappingConfigFactory().process();
    }
}